Section A: Data Structures & Control Structures

In [ ]:
#1 .Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
#creating the list of 5  integers

a = [5,12,23,45,67,86]
print(type(a))
print("1.The list is :",a)

#append
a.append(5)
print("2.the list after appending the value 5:",a) 

#extend
a.extend('vis')
print("3.the list after extending (vis) :",a)

#insert
a.insert(5,10)
print("4.The list after inserting (5,10):",a)

#remove
a.remove(a[1])
print("5.the list after removing index 1:",a)

#pop
pop = a.pop(2)
print(f"pop value is :",pop)
print("6.the list after pop the 2 index: ",a)

#index
index = a.index('v')
print(f"7.the index value of v:",index)

#count
count = a.count(5)
print(f"8.the number of 5 available in a list is  :" ,count)

#reverse
a.reverse()
print("9.The reverse of list is :",a)

#sort
b= [x for x in a if type(x) == int or type(x) == float]  #here we are taking only int and float so the string variable will be removed
b.sort()
print("10.The sorted list is :",b)

#clear
a.clear()
print("11.clearing the list :",a)


<class 'list'>
1.The list is : [5, 12, 23, 45, 67, 86]
2.the list after appending the value 5: [5, 12, 23, 45, 67, 86, 5]
3.the list after extending (vis) : [5, 12, 23, 45, 67, 86, 5, 'v', 'i', 's']
4.The list after inserting (5,10): [5, 12, 23, 45, 67, 10, 86, 5, 'v', 'i', 's']
5.the list after removing index 1: [5, 23, 45, 67, 10, 86, 5, 'v', 'i', 's']
pop value is : 45
6.the list after pop the 2 index:  [5, 23, 67, 10, 86, 5, 'v', 'i', 's']
7.the index value of v: 6
8.the number of 5 available in a list is  : 2
9.The reverse of list is : ['s', 'i', 'v', 5, 86, 10, 67, 23, 5]
10.The sorted list is : [5, 5, 10, 23, 67, 86]
11.clearing the list : []


2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [ ]:
names = ('vishnu','sakthi','sundar')
print(type(names))  #to show this is an tuple

names[1] = 'kumar'   
''' it prints error as 
TypeError: 'tuple' object does not support item assignment 

Reason : tuples are immutable (immutable means that we cannot change once assigned )'''

<class 'tuple'>


TypeError: 'tuple' object does not support item assignment

3.	Create a set of integers with some duplicate values. Print the set and explain the output.

In [ ]:
num =  {10,12,12,10,15,24}
print(type(num))
print(num)

'''The output of this set is :
<class 'set'>
{24, 10, 12, 15}

sets actually removes the duplicates and gives out the unique value'''


<class 'set'>
{24, 10, 12, 15}


"The iutput of this set is :\n<class 'set'>\n{24, 10, 12, 15}\n\nsets actually removes the duplicates and gives out the unique value"

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [29]:
dictionary = {'name':'vishnu' , 'age':24 , "city": 'kanyakumari'}
print(type(dictionary))
print(dictionary)
#update the age
dictionary['age'] = 26
print("The dict after updating the age :",dictionary)

#adding new key email to the dict
dictionary['email']='svsathieshvishnu194@gmail.com'
print("the final dict is :",dictionary)


<class 'dict'>
{'name': 'vishnu', 'age': 24, 'city': 'kanyakumari'}
The dict after updating the age : {'name': 'vishnu', 'age': 26, 'city': 'kanyakumari'}
the final dict is : {'name': 'vishnu', 'age': 26, 'city': 'kanyakumari', 'email': 'svsathieshvishnu194@gmail.com'}


5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [32]:
age  = int(input("Enter the age to check the eligibility: "))
if age >= 18:
    print(f"The age({age}) is eligible to vote")
else:
    print(f"The age({age}) is not eligible to vote")

The age(19) is eligible to vote


6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [38]:
marks = int(input("Enter the mark :"))

if marks >= 90 :
    print(f"The Grade of {marks} is A")
elif marks >= 75 and  marks <=89:
    print(f"The Grade of {marks} is B")
elif marks >= 50 and marks <=74:
    print(f"The Grade of {marks} is c")
else:
    print(f"The mark is {marks} and grade is fail")
     

The Grade of 99 is A


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [43]:
num = int(input("Enter the number :"))

if(num>0 and num%2 == 0):
    print(f"the number ({num}) is positive and even")
elif(num>0 and num%2 == 1):
    print(f"the number ({num}) is positive and odd")
else:
    print(f"the number ({num}) is zero or negative")

the number (-10) is zero or negative


Section B:Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [1]:
import numpy as np

In [14]:
scalar = np.array(5)
print(f'A scalar using np.array(5) is {scalar}')

one_d_array = np.array([1,2,3,4,5])
print(f'\nA 1D array with values 1 to 5 is {one_d_array}')

two_d_array = np.arange(10,70,10).reshape(2,3)
print(f'\nA 2D array (2x3) with values from 10 to 60 in steps of 10 is \n{two_d_array}')



A scalar using np.array(5) is 5

A 1D array with values 1 to 5 is [1 2 3 4 5]

A 2D array (2x3) with values from 10 to 60 in steps of 10 is 
[[10 20 30]
 [40 50 60]]


9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [10]:
import numpy as np

In [13]:
array = np.random.randint(0,101, size = (4,4))
print(f'A 4x4 Numpy array of random integers between 0 and 100 is\n {array}')

A 4x4 Numpy array of random integers between 0 and 100 is
 [[41 18 39 61]
 [97 79 45 30]
 [66 91 21  1]
 [ 5 21 77 27]]


10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [15]:
import numpy as np
import pandas as pd 

In [ ]:
arr = np.random.randint(1,20 , size=(3,3))   # we are taking random numbers to create 2d array in size 3x3 
print(f"the created 2d array with size 3x3 is \n{arr}")

the created 2d array with size 3x3 is 
[[19  3  3]
 [ 1  7  6]
 [ 1  4 12]]


In [ ]:
df = pd.DataFrame(arr,columns=('A','B','C')) #we are taking the created arr and reading with pandas as dataframe and also give the column name to it  as ('A','B','C')
print(f"The numpy converts to dataframe with column name as ('A','B','C') :\n{df} ")

The numpy converts to dataframe with column name as ('A','B','C') :
    A  B   C
0  19  3   3
1   1  7   6
2   1  4  12 


Section C: Exploring Pandas

1.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [66]:
import numpy as np
import pandas as pd

In [67]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Ethan', 'Fiona', 'George', 'Hannah', 'Ian', 'Julia'],
    'Age':  [28, 34, 23, 45, 31, 29, 52, 38, 26, 41],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
    'Salary': [70000, 85000, 52000, 120000, np.nan, 68000, 110000, 76000, 54000, 99000]
}

In [68]:
df = pd.DataFrame(data)

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  9 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [70]:
df.describe()

Age         Salary
count  10.00000       9.000000
mean   34.70000   81555.555556
std     9.18997   23937.998617
min    23.00000   52000.000000
25%    28.25000   68000.000000
50%    32.50000   76000.000000
75%    40.25000   99000.000000
max    52.00000  120000.000000

In [71]:
print(f"Data after selecting the name and city is \n {df[['Name', 'City']]}")

Data after selecting the name and city is 
       Name          City
0    Alice      New York
1      Bob   Los Angeles
2  Charlie       Chicago
3    Diana       Houston
4    Ethan       Phoenix
5    Fiona  Philadelphia
6   George   San Antonio
7   Hannah     San Diego
8      Ian        Dallas
9    Julia      San Jose


In [72]:
droped = df.drop(columns=['City'])
print(f'Data after deleting the column city : \n{drop}')

Data after deleting the column city : 
      Name  Age  Salary
0    Alice   28   70000
1      Bob   34   85000
2  Charlie   23   52000
3    Diana   45  120000
4    Ethan   31   95000
5    Fiona   29   68000
6   George   52  110000
7   Hannah   38   76000
8      Ian   26   54000
9    Julia   41   99000


In [73]:
#checking the null values in the data 
print(df.isnull().sum())


Name      0
Age       0
City      0
Salary    1
dtype: int64


In [81]:
#fill the null values with mean 

mean_Salary = droped['Salary'].mean()
droped['Salary'].fillna(droped['Salary'].mean(), inplace=True)
print(f"Data after filling the null value using mean is \n{droped}")



Data after filling the null value using mean is 
      Name  Age         Salary
0    Alice   28   70000.000000
1      Bob   34   85000.000000
2  Charlie   23   52000.000000
3    Diana   45  120000.000000
4    Ethan   31   81555.555556
5    Fiona   29   68000.000000
6   George   52  110000.000000
7   Hannah   38   76000.000000
8      Ian   26   54000.000000
9    Julia   41   99000.000000


C:\Users\hp\AppData\Local\Temp\ipykernel_18104\2468123503.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  droped['Salary'].fillna(droped['Salary'].mean(), inplace=True)


In [77]:
print(droped.isnull().sum())# checking for any other null values present in it 

Name      0
Age       0
Salary    0
dtype: int64


In [80]:
#removing any duplicate row if present 

duplicate = droped.drop_duplicates()
print(f'The data after removing duplicate rows \n{duplicate}')

The data after removing duplicate rows 
      Name  Age         Salary
0    Alice   28   70000.000000
1      Bob   34   85000.000000
2  Charlie   23   52000.000000
3    Diana   45  120000.000000
4    Ethan   31   81555.555556
5    Fiona   29   68000.000000
6   George   52  110000.000000
7   Hannah   38   76000.000000
8      Ian   26   54000.000000
9    Julia   41   99000.000000
